//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Proyecto_GRM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Mantenimientos
    {
        public int MantenimientoId { get; set; }

        [Required]  // Data validator
        [Display(Name = "Vehículo")]   // Manda el name de lo que falta
        public int VehiculoId { get; set; }

        [Required]  // Data validator
        [Display(Name = "Nota")]   // Manda el name de lo que falta
        public string Nota { get; set; }

        [Required]  // Data validator
        [Display(Name = "Fecha")]   // Manda el name de lo que falta
        //[DataType(DataType.Date)]
        public System.DateTime Fecha { get; set; }
    
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
