//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Proyecto_GRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Mantenimientos
    {
        public int MantenimientoId { get; set; }
        public int VehiculoId { get; set; }
        public string Vehiculo { get; set; }
        public string Nota { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
